extern "C" __declspec(dllexport) void utSetString() {}
extern "C" __declspec(dllexport) void utSetNumber() {}
extern "C" __declspec(dllexport) void utSetFloat() {}
extern "C" __declspec(dllexport) void utSetBoolean() {}
extern "C" __declspec(dllexport) void utSetDate() {}
extern "C" __declspec(dllexport) void utSetCurrentDate() {}
extern "C" __declspec(dllexport) void utSetObject() {}
extern "C" __declspec(dllexport) void utRemoveProperty() {}
extern "C" __declspec(dllexport) void utCreateEvent() {}
extern "C" __declspec(dllexport) void utGetEventJson() {}
extern "C" __declspec(dllexport) void utDestroyEvent() {}
extern "C" __declspec(dllexport) void utCreateEventObject() {}
extern "C" __declspec(dllexport) void utCreateEventArray() {}
extern "C" __declspec(dllexport) void utPushString() {}
extern "C" __declspec(dllexport) void utPushInt() {}
extern "C" __declspec(dllexport) void utPushFloat() {}
extern "C" __declspec(dllexport) void utPushObject() {}
extern "C" __declspec(dllexport) void utCreateSchemaFilter() {}
extern "C" __declspec(dllexport) void utDestroySchemaFilter() {}
extern "C" __declspec(dllexport) void utFilterEvent() {}
extern "C" __declspec(dllexport) void utGetJsTime() {}
extern "C" __declspec(dllexport) void utGetTracingId() {}
extern "C" __declspec(dllexport) void utCreateEventFromJson() {}
extern "C" __declspec(dllexport) void utGetSbahnDispatchUrl() {}
