extern "C" __declspec(dllexport) void utCreateService() {}
extern "C" __declspec(dllexport) void utDestroyService() {}
extern "C" __declspec(dllexport) void utServiceInit() {}
extern "C" __declspec(dllexport) void utGetTestConfig() {}
extern "C" __declspec(dllexport) void utSetTestConfig() {}
extern "C" __declspec(dllexport) void utServiceGetEventsInQueueLength() {}
extern "C" __declspec(dllexport) void utServiceSetDeviceWs1Setting() {}
extern "C" __declspec(dllexport) void utServiceSetUserInt() {}
extern "C" __declspec(dllexport) void utServiceSetUserString() {}
extern "C" __declspec(dllexport) void utServiceSetUserBoolean() {}
extern "C" __declspec(dllexport) void utServiceRemoveUser() {}
extern "C" __declspec(dllexport) void utGetServiceState() {}
extern "C" __declspec(dllexport) void utServiceStart() {}
extern "C" __declspec(dllexport) void utServiceStop() {}
extern "C" __declspec(dllexport) void utCreateStaticServiceTransport() {}
extern "C" __declspec(dllexport) void utApplyServiceConfigEventSchema() {}
extern "C" __declspec(dllexport) void utGetServiceConfig() {}
extern "C" __declspec(dllexport) void utSetServiceConfig() {}
extern "C" __declspec(dllexport) void utServiceSetLogCallback() {}
extern "C" __declspec(dllexport) void utServiceDispatchRecord() {}
extern "C" __declspec(dllexport) void utSetAuthToken() {}
extern "C" __declspec(dllexport) void utServicePushAdobeReportSuite() {}
extern "C" __declspec(dllexport) void utServiceGetCommonPropertiesObject() {}
