extern "C" __declspec(dllexport) void utCreateClient() {}
extern "C" __declspec(dllexport) void utDestroyClient() {}
extern "C" __declspec(dllexport) void utInitClient() {}
extern "C" __declspec(dllexport) void utGetUserClockTimestamp() {}
extern "C" __declspec(dllexport) void utDispatch() {}
extern "C" __declspec(dllexport) void utUserDispatch() {}
extern "C" __declspec(dllexport) void utDispatchRecord() {}
extern "C" __declspec(dllexport) void utGetCommonPropertiesObject() {}
extern "C" __declspec(dllexport) void utCreateObject() {}
extern "C" __declspec(dllexport) void utApplyObjectToEvent() {}
extern "C" __declspec(dllexport) void utSetClientTransport() {}
